### ISSUE TITLE
Cannot build: no matching versions for query "latest"

### ISSUE THREAD

**Issue by TFKls** [pibuxd/vanilla#2]
I've cloned the repository and attempted to build this program.
I am getting an error when running the Makefile, picture of which I've attached below. 
![image](https://user-images.githubusercontent.com/43710501/103139607-4c329700-46de-11eb-9efd-59e243802a5b.png)

**Comment by TFKls** [comment]
**Additional info**:
Build using Go 1.15.5 on linux/amd64

**Comment by pibuxd** [comment]
Sometimes I push it to have a backup of vanilla :), if vanilla will work I will create an official release. Also, I'm inventing new solutions for handling.

**Comment by pibuxd** [comment]
today I'm repairing lots of things, it will be much simpler and faster :)))))))

**Comment by TFKls** [comment]
Can you tell me to which commit I should revert the repository will build successfully? Please give the commit hash, as looking by the names there are multiple commits with the same names (tip: you can amend commits).
Also, shouldn't the default branch be stable after the initial commit? Or at least please could you be willing to have some stable branch.
Also, I recommend deleting the PR branch add-license-1, as it serves no purpose anymore.

**Comment by TFKls** [comment]
> Sometimes I push it to have a backup of vanilla :), if vanilla will work I will create an official release. Also, I'm inventing new solutions for handling.

Note: the official release that has been put out is busted, as go tries to pull the repo from the default github branch.
