### ISSUE TITLE
Program doesn't have way to disable color.

### ISSUE THREAD

**Issue by tfkls** [pibuxd/vanilla#3]
When piping to files, all the ANSI escape codes are kept.
This depends if you desire for the package manager, but as it stands it will not work on terminals with no color support.
It would be useful for there to be an option to disable the coloring.

**Comment by cloud11665** [comment]
encountered the same problem. Could use [this](https://stackoverflow.com/questions/2465425/how-do-i-determine-if-a-terminal-is-color-capable) to fix it.

**Comment by cloud11665** [comment]
@pibuxd

**Comment by pibuxd** [comment]
it won't, sorry
